name: flutter_test_ui
description: Wrapper for flutter_test that adds a tester argument to setUp and tearDown functions
version: 1.0.0
homepage: https://github.com/spkersten/flutter_test_ui

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ">=1.1.5 <2.0.0"

flutter:
